# docker-compose up -d --build

version: '3.8'

services:
  app:
    build: ./app
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
    env_file:
      - .env

  db:
    container_name: db
    build: ./postgres-setup
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: