# docker-compose up -d --build

version: '3.8'

services:
  app:
    build: ./app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
        # condition: service_healthy
    links:
      - db
    env_file:
      - .env

  db:
    container_name: mydatabase
    restart: always
    build: ./postgres-setup
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

volumes:
  db_data: