# to start the application : docker-compose up --build

version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres
    environment:
    - POSTGRES_USER=myuser
    - POSTGRES_DB=mydb
    - POSTGRES_PASSWORD=mypassword
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: